cropped_size:  896
image_size: 1024
tl_model: 'Resnet34'
output_dim: 1
hidden_dim: 512
batch_size: 8
margin: 2.0
mode: "prev"
gamma: 1.0
layer_dim: 1
n_times: 2
learning_rate: 0.0001
num_epoch: 100
dropout: 0.1
weight_decay: 0.0005
imb_mode: "None"
types: "baseline"
setting: 1
pretrained: True
fold: 1
year: "4yr"
